"""add comments fields

Revision ID: 05e9fce9a371
Revises: 33307a2b0ed8
Create Date: 2025-11-05 17:14:15.979049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05e9fce9a371'
down_revision: Union[str, Sequence[str], None] = '33307a2b0ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover foreign key constraint do username em comentario
    # Como a constraint foi criada sem nome explícito na migration inicial,
    # precisamos encontrá-la dinamicamente
    from sqlalchemy import inspect
    
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Buscar todas as foreign keys na tabela comentario
    foreign_keys = inspector.get_foreign_keys('comentario')
    
    # Remover foreign key que referencia user.username
    for fk in foreign_keys:
        if 'username' in fk.get('constrained_columns', []) and 'username' in fk.get('referred_columns', []):
            op.drop_constraint(
                fk['name'],
                'comentario',
                type_='foreignkey'
            )
            break  # Remover apenas a primeira encontrada
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Recriar foreign key do username (se necessário reverter)
    op.create_foreign_key(
        None,
        'comentario',
        'user',
        ['username'],
        ['username']
    )
    # ### end Alembic commands ###
