"""add user and coments fiels

Revision ID: 33307a2b0ed8
Revises: cda8e3985d10
Create Date: 2025-11-05 17:10:15.077036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '33307a2b0ed8'
down_revision: Union[str, Sequence[str], None] = 'cda8e3985d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contato', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contato')
    # ### end Alembic commands ###
