"""initial

Revision ID: c1dae1e5035d
Revises: 
Create Date: 2025-09-29 21:47:24.486242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c1dae1e5035d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_ocorrencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_acorrencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovada', 'rejeitada', name='statusclaim'), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('objeto_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['objeto_id'], ['objeto.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user', ['username'])
    op.add_column('comentario', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'comentario', 'user', ['username'], ['username'])
    op.add_column('objeto', sa.Column('url_imagem', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('objeto', 'url_imagem')
    op.drop_constraint(None, 'comentario', type_='foreignkey')
    op.drop_column('comentario', 'username')
    op.drop_table('claim')
    # ### end Alembic commands ###
