"""fix field name

Revision ID: cda8e3985d10
Revises: fc954516fdfc
Create Date: 2025-10-29 19:41:31.551081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cda8e3985d10'
down_revision: Union[str, Sequence[str], None] = 'fc954516fdfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('data_ocorrencia', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('claim', 'data_acorrencia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('data_acorrencia', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('claim', 'data_ocorrencia')
    # ### end Alembic commands ###
