"""remove_username_foreign_key_from_comentario

Revision ID: f27932b2f07a
Revises: 05e9fce9a371
Create Date: 2025-11-05 17:34:38.084908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f27932b2f07a'
down_revision: Union[str, Sequence[str], None] = '05e9fce9a371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comentario_username_fkey'), 'comentario', type_='foreignkey')
  # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('comentario_username_fkey'), 'comentario', 'user', ['username'], ['username'])
    # ### end Alembic commands ###
