"""add tables

Revision ID: fc954516fdfc
Revises: c1dae1e5035d
Create Date: 2025-10-19 12:08:33.900518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc954516fdfc'
down_revision: Union[str, Sequence[str], None] = 'c1dae1e5035d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('claim', sa.Column('evidencias', sa.JSON(), nullable=True))
    op.add_column('claim', sa.Column('tutor_id', sa.Uuid(), nullable=False))
    op.alter_column('claim', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'local_ocorrencia',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('claim', 'data_acorrencia',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'claim', 'user', ['tutor_id'], ['id'])
    op.add_column('objeto', sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objeto', 'categoria')
    op.drop_constraint(None, 'claim', type_='foreignkey')
    op.alter_column('claim', 'data_acorrencia',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'local_ocorrencia',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claim', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('claim', 'tutor_id')
    op.drop_column('claim', 'evidencias')
    op.drop_table('notification')
    # ### end Alembic commands ###
